### ISSUE TITLE
API not working anymore?

### ISSUE THREAD

**Issue by SimonBirrell** [girishso/goog_currency#6]
This was working for me a few days ago. Now, when I execute from the console:

```
GoogCurrency.usd_to_brl(100)
```

I'm getting the following error message:

```
JSON::ParserError: 757: unexpected token at '<!doctype html><html class="google gws-header" lang="en"> <head> <meta charset="utf-8"> <title>What happened to iGoogle? - Search Help</title> <link href="//www.gstatic.com/" rel="dns-prefetch"> <link href="https://support.google.com/websearch/answer/2664197?hl=en" rel="canonical"> <link href="https://support.google.com/websearch/answer/2664197?hl=ar" hreflang="ar" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=zh-Hant" hreflang="zh-Hant" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=bg" hreflang="bg" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=pt-BR" hreflang="pt-BR" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=zh-Hans" hreflang="zh-Hans" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=da" hreflang="da" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=de" hreflang="de" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=el" hreflang="el" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=en" hreflang="en" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=es" hreflang="es" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=fi" hreflang="fi" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=fr" hreflang="fr" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=hi" hreflang="hi" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=hu" hreflang="hu" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=it" hreflang="it" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=iw" hreflang="iw" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=ja" hreflang="ja" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=ko" hreflang="ko" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=nl" hreflang="nl" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=no" hreflang="no" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=pl" hreflang="pl" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=ro" hreflang="ro" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=ru" hreflang="ru" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=sk" hreflang="sk" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=sl" hreflang="sl" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=sv" hreflang="sv" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=th" hreflang="th" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=tr" hreflang="tr" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=fil" hreflang="fil" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=cs" hreflang="cs" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=id" hreflang="id" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=eu" hreflang="eu" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=ca" hreflang="ca" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=gl" hreflang="gl" rel="alternate"><link href="https://support.google.com/websearch/answer/2664197?hl=ms" hreflang="ms" rel="alternate"> <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"> <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"> <meta content="&lt;p&gt;iGoogle was retired on November 1, 2013. The mobile version was retired on July 31, 2012.&lt;/p&gt;&#10;&#10;&lt;p&gt;&lt;strong&gt;How did you come to this decision?&lt;/strong&gt;&lt;br /&gt;&#10;  We originally launched iGoogle in 2005 " name="description"> <meta content="Google Help Center" name="keywords">  <meta content="follow,index" name="robots">  <link href="//support.google.com/favicon.ico" rel="shortcut icon" type="image/x-icon">  <link href="https://www.google.com/css/maia.css" rel="stylesheet">   <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">   <link href="//www.gstatic.com/support/content/20131031-164550-0748/css/v2/hc-all.css" rel="stylesheet">         <script>(function(){var b=window,e="tick";(function(){function f(a){this.t={};this.tick=function(a,c,d){this.t[a]=[void 0!=d?d:(new Date).getTime(),c]};this[e]("start",null,a)}var a=new f;b.jstiming={Timer:f,load:a};if(b.performance&&b.performance.timing){var a=b.performance.timing,c=b.jstiming.load,d=a.navigationStart,a=a.responseStart;0<d&&a>=d&&(c[e]("_wtsrt",void 0,d),c[e]("wtsrt_","_wtsrt",a),c[e]("tbsd_","wtsrt_"))}try{a=null,b.chrome&&b.chrome.csi&&(a=Math.floor(b.chrome.csi().pageT),c&&0<d&&(c[e]("_tbnd",void 0,b.chrome.csi().startE),c[e]("tbnd_","_tbnd",d))),null==a&&b.gtbExternal&&(a=b.gtbExternal.pageT()),null==a&&b.external&&(a=b.external.pageT,c&&0<d&&(c[e]("_tbnd",void 0,b.external.startE),c[e]("tbnd_","_tbnd",d))),a&&(b.jstiming.pt=a)}catch(g){}})();})();</script>  <script>(function(H){H.className=H.className.replace(/\bgoogle\b/,'google-js')})(document.documentElement)
</script>  <script src="https://www.google.com/js/google.js"></script> <script>var hcfeComponents = [];var hcfeFormModels = {};var hcfeStrings = {};var formFunctions = {};</script>  </head> <body> <header class="primary-header nocontent">  <div class="searchbar-container"> <div class="searchbar" data-tracking-cat="searchbar"><div class="logo-container"><a href="//www.google.com/"><img src="//www.google.com/help/hc/images/google_logo_116x41.png" alt="Google Logo" height="41" width="116"></a></div><div class="mobile-toggles"><div class="mobile-button mobile-button--search-toggle" id="search-toggle"><div></div></div></div><div class="search-container" id="search-container"><form class="primary-search" action="/websearch/search?hl=en" id="search-form" role="search"><input value="en" name="hl" type="hidden"><input class="search-box jfk-textinput" placeholder="Search Help" value="" autocomplete="off" id="search-box" name="query" spellcheck="false" type="search"><button class="jfk-button jfk-button-action" id="search-button" type="submit"><img class="jfk-button-img" src="//ssl.gstatic.com/ui/v1/button/search-white.png" height="21" width="21" alt="raw:hc_model.page_strings.search_product_help_short"></button></form><script>(function(){var cse_cx='+qptype:1';hcfeComponents.push(['hcfe','Search','.primary-search',{'isOneGoogleBar':false,'searchCx':cse_cx
}]);})();</script></div><script>hcfeComponents.push(['hcfe','SearchToggle','.mobile-button--search-toggle']);</script><div class="user-info"><div class="sign-in jfk-button jfk-button-standard goog-inline-block" data-tracking-delay-url="//www.google.com/accounts/ServiceLogin?&amp;continue=https://support.google.com/websearch/answer/2664197" data-tracking-action="sign in button" data-tracking-method="DELAY">Sign in</div><script>hcfeComponents.push(['hcfe','UserInfo','.user-info']);</script></div></div> </div> <div class="appbar-container"><div class="appbar" data-tracking-cat="appbar"><nav class="appbar-nav"><ul><li><a class="product-icon" href="javascript:;"><img alt="Search" src="//www.google.com/images/icons/product/search-16.png"></a><ul class="product-links"><li><a href="http://www.google.com/intl/en/insidesearch/index.html">Home</a></li><li><a href="http://www.google.com/intl/en/insidesearch/howsearchworks/thestory/">How Search Works</a></li><li><a href="http://www.google.com/intl/en/insidesearch/tipstricks/index.html">Tips & Tricks</a></li><li><a href="http://www.google.com/intl/en/insidesearch/features/">Features</a></li><li><a href="http://www.google.com/intl/en/insidesearch/stories/index.html">Search Stories</a></li><li><a href="http://www.google.com/intl/en/insidesearch/playground/">Playground</a></li><li><a href="http://insidesearch.blogspot.com/">Blog</a></li><li><a href="http://support.google.com/websearch/?hl=en">Help</a></li><li><a href="//support.google.com/?hl=en">Help for other Google products</a></li></ul><script>hcfeComponents.push(['hcfe','ProductLinks','.appbar-nav .product-icon']);</script><a class="crumb product-name" href="//www.google.com/">Search</a></li><li class="crumb-container" style="z-index:1"><a class="crumb crumb--first crumb--last" href="/websearch/?hl=en#topic=3378866"><span title="Help">Help</span></a></li><li></li></ul></nav><div class="appbar-buttons"><a href="javascript:;" data-tracking-cat="Escalation Flow" class="esc-flow-anchor escalation-button" data-tracking-action="trigger - header">Contact Us</a><a class="community-button" href="//productforums.google.com/forum/#!forum/websearch" target="_blank">Community</a></div></div></div>  <div class="info-bar-container info-bar-container--notification">    <div class="notification notification--info-bar" data-name="duffman_launch" data-tracking-cat="Notification: duffman_launch" data-tracking-impression=""><p>Have 1 minute to spare? <a href="//s.userzoom.com/m/MSBDNlM0ODIg">Help us improve the Search help center.</a></p><a class="dismiss-link" href="javascript:;" data-tracking-action="dismiss"></a></div> <script>(function(){var passDismissKey='Notification__duffman_launch__Timestamp';var passImpressionCounter=0;var passImpressionKey='Notification__duffman_launch__Count';var passStorageType=2;hcfeComponents.push(['hcfe','notifications.Notification','.notification',{dismissKey:passDismissKey,impressionCounter:passImpressionCounter,impressionKey:passImpressionKey,storageType:passStorageType
}]);})();</script>  </div>   </header> <section class="primary-container"><div class="page-width-container"><article class="primary-article primary-article--answer" role="main">   <div class="article-container" data-tracking-cat="article-container">  <h1>What happened to iGoogle?</h1>    <div class="main-section--answer main-section content-container"><p>iGoogle was retired on November 1, 2013. The mobile version was retired on July 31, 2012.</p>

<p><strong>How did you come to this decision?</strong><br>
  We originally launched iGoogle in 2005 before anyone could fully imagine the ways that today's web and mobile apps would put personalized, real-time information at your fingertips. With modern apps that run on platforms like Chrome&nbsp;and Android, the need for something like iGoogle has eroded over time.</p>

<p><strong>What will happen to the data stored in my gadgets?</strong><br>
  All of your personal data stored in other Google products will continue to be available via those products, including <a href="https://www.mail.google.com" target="_blank">Gmail</a>, <a href="https://www.google.com/calendar/" target="_blank">Google Calendar</a>, <a href="https://www.google.com/finance" target="_blank">Google Finance</a>, <a href="https://www.drive.google.com" target="_blank">Google Drive</a>, <a href="https://www.google.com/bookmarks" target="_blank">Google Bookmarks</a>, and <a href="//www.mail.google.com/tasks" target="_blank">Google Tasks</a>. This means you'll still be able to access your emails, documents and events. Instead of accessing your data through the gadget, you'll need to visit the product directly. &nbsp;</p>

<p>Most iGoogle gadgets are created and maintained by third-party developers. If youd like to export your data, you should contact the gadget creator directly.</p>

<p><strong>I really like iGoogle -- are there any other alternatives?</strong></p>

<p>There are a number of desktop <a href="http://alternativeto.net/software/igoogle/" target="_blank">alternatives available</a>.&nbsp;If youre a fan of Google Chrome, the&nbsp;<a href="//chrome.google.com/webstore" target="_blank">Chrome Web Store</a>&nbsp;provides a similar range of options like&nbsp;<a href="//chrome.google.com/webstore/category/app/7-productivity" target="_blank">productivity tools</a>&nbsp;and applications to&nbsp;<a href="//chrome.google.com/webstore/category/app/65-weather-forecasts" target="_blank">check the weather</a>. In addition, just like iGoogle, you can&nbsp;<a href="//chrome.google.com/webstore/category/themes" target="_blank">personalize Chrome</a>&nbsp;with a theme.</p>

<p>For mobile devices, Google Play offers applications ranging from games to news readers to home screen widgets.</p>

<p>&nbsp;</p>
</div>     </div>  <script>hcfeComponents.push(['hcfe','RelatedItemsFooter','.related-item--youtube']);</script>    </article><script>hcfeComponents.push(['hcfe','PrimaryArticle','.primary-article']);</script><div class="nocontent primary-nav primary-nav--sibling" role="navigation"><nav><div class="sibling-nav" data-tracking-cat="sibling-nav"><h4><a class="title-link" href="/websearch/?hl=en#topic=3378866">Help</a></h4><ul class="sibling-list"><li><a href="javascript:;" class="sibling-link sibling-link--current">What happened to iGoogle?</a></li><li><a href="/websearch/answer/510?hl=en&amp;ref_topic=3378866" class="sibling-link">SafeSearch: Turn on or off</a></li><li><a href="/websearch/answer/179386?hl=en&amp;ref_topic=3378866" class="sibling-link">Location settings</a></li><li><a href="/websearch/answer/86640?hl=en&amp;ref_topic=3378866" class="sibling-link">"Unusual traffic from your computer network" notification</a></li><li><a href="/websearch/answer/186645?hl=en&amp;ref_topic=3378866" class="sibling-link">Google Instant doesn't work</a></li><li><a href="/websearch/answer/106230?hl=en&amp;ref_topic=3378866" class="sibling-link">Autocomplete</a></li><li><a href="/websearch/answer/465?hl=en&amp;ref_topic=3378866" class="sibling-link">Delete search history</a></li><li><a href="/websearch/answer/463?hl=en&amp;ref_topic=3378866" class="sibling-link">Make Google my homepage</a></li></ul></div></nav></div><script>hcfeComponents.push(['hcfe','NavPanel','.primary-nav']);</script></div></section><script>window.jstiming.load.tick('prt');</script> <footer class="primary-footer nocontent" role="contentinfo">  <div class="secondary-footer-container"> <div class="secondary-footer"> <div class="article-survey-container"> <div class="article-survey article-survey--disabled"><h4>How helpful is this article:</h4><div class="selected-text"></div><div class="recorded-message">Feedback recorded. Thanks!</div><ul class="ratings"><li data-rating="1">Not at all helpful</li><li data-rating="2">Not very helpful</li><li data-rating="3">Somewhat helpful</li><li data-rating="4">Very helpful</li><li data-rating="5">Extremely helpful</li></ul><div class="goog-slider"><div class="goog-slider-scale"></div><div class="goog-slider-thumb"></div></div><div class="form form--hidden" data-form="article_survey_full"></div></div> </div>  <div class="plus-one-container">  <div class="plus-button" data-tracking-cat="plus-button"> </div> <script>hcfeComponents.push(['hcfe','PlusButton','.plus-button']);</script>  </div> </div> <script>hcfeComponents.push(['hcfe','ArticleSurvey','.article-survey']);</script> </div> <div class="footer-links-container"> <div class="footer-links" data-tracking-cat="footer-standard"> <ul> <li> 2013 Google </li> <li> <a href="//www.google.com/intl/en/privacy.html">Privacy Policy</a> </li> <li> <a href="//www.google.com/accounts/TOS">Terms of Service</a> </li>  </ul>  <form action="#" class="language-selector" method="get"> <select name="hl"> <option value="ar">&rlm;</option><option value="bg">&lrm;</option><option value="ca">catal&lrm;</option><option value="cs">etina&lrm;</option><option value="da">dansk&lrm;</option><option value="de">Deutsch&lrm;</option><option value="el">&lrm;</option><option value="en" selected="selected">English&lrm;</option><option value="es">espaol&lrm;</option><option value="eu">euskara&lrm;</option><option value="fi">suomi&lrm;</option><option value="fil">Filipino&lrm;</option><option value="fr">franais&lrm;</option><option value="gl">galego&lrm;</option><option value="hi">&lrm;</option><option value="hu">magyar&lrm;</option><option value="id">Bahasa Indonesia&lrm;</option><option value="it">italiano&lrm;</option><option value="iw">&rlm;</option><option value="ja">&lrm;</option><option value="ko">&lrm;</option><option value="ms">Bahasa Melayu&lrm;</option><option value="nl">Nederlands&lrm;</option><option value="no">norsk&lrm;</option><option value="pl">polski&lrm;</option><option value="pt-BR">portugus (Brasil)&lrm;</option><option value="ro">romn&lrm;</option><option value="ru">&lrm;</option><option value="sk">slovenina&lrm;</option><option value="sl">slovenina&lrm;</option><option value="sv">svenska&lrm;</option><option value="th">&lrm;</option><option value="tr">Trke&lrm;</option><option value="zh-Hans">&lrm;</option><option value="zh-Hant">&lrm;</option> </select> <noscript> <input type="submit"> </noscript> </form> <script>hcfeComponents.push(['hcfe','LanguageSelector','.language-selector']);</script>    </div> </div> </footer> <div class="esc-flow-content" data-tracking-cat="Escalation Flow"> <div class="slider"> <div class="title-bar"> <nav> <a class="back-link" href="javascript:;" data-tracking-action="back link" role="button">Back</a> </nav> <h3>Contact Us</h3> </div>  <section class="left-pane">  <div class="top-section"> <div> <div class="issue-ts"></div> <div class="recommended-answers"> <p>The following articles may help you resolve your issue right away. If the articles don't address your issue, try the contact options below. You can quickly return to this page after visiting an article.</p> <ul></ul> </div> <p class="options-prompt">Still need help? To contact the support team, click below.</p> <div class=""error"-message"><p>Oops! Looks like something went wrong. Please try again.<br>If you still get an "error", please try again in a day or two. We're on it.</p></div> </div> </div> <div class="activity-indicator"></div> </section> <section class="drawer"> <div class="button-bar"> <div class="email-btn goog-inline-block jfk-button jfk-button-action">Email</div> <div class="phone-btn goog-inline-block jfk-button jfk-button-action">Phone</div> <div class="chat-btn goog-inline-block jfk-button jfk-button-action">Chat</div> <div class="options-status"> <div class="chat-unavailable"></div> <div class="phone-unavailable">Phone specialists are currently offline.</div> <div class="both-unavailable">Chat and phone specialists are currently offline.</div> <div class="chat-insession"></div> </div> </div> <div class="issue-contact-form"> </div> </section> <section class="right-pane"> <article> </article> </section> </div> </div><script>(function(){var c2cAvail=false;var chatFormId='';var chatPoolId='';var contactParam='';var loginPrompt=false;var nodeList=[{topic_id:'3104520'},{topic_id:'3111061'},{topic_id:'2889052'},{topic_id:'2889025'},{topic_id:'2889055'},{topic_id:'2889056'},{topic_id:'2889026'},{topic_id:'2889054'},{topic_id:'2889029'},{topic_id:'2889099'},{topic_id:'2889102'},{topic_id:'2889063'},{topic_id:'2889104'},{topic_id:'2889076'},{topic_id:'2889115'},{topic_id:'3143868'},{topic_id:'2889077'},{topic_id:'2902466'},{topic_id:'2902569'},{topic_id:'2902572'},{topic_id:'2902574'},{topic_id:'2902600'},{topic_id:'2902575'},{topic_id:'2902601'},{topic_id:'2902570'},{topic_id:'2902572'},{topic_id:'2902574'},{topic_id:'2902600'},{topic_id:'2902575'},{topic_id:'2902601'},{topic_id:'2902505'},{topic_id:'2902572'},{topic_id:'2902574'},{topic_id:'2902600'},{topic_id:'2902575'},{topic_id:'2902601'},{topic_id:'2902504'},{topic_id:'2902572'},{topic_id:'2902574'},{topic_id:'2902600'},{topic_id:'2902575'},{topic_id:'2902601'},{topic_id:'2902531'},{topic_id:'2889112'},{topic_id:'2889113'},{topic_id:'2946651'},{topic_id:'2946654'},{topic_id:'2946656'},{topic_id:'2946659'},{topic_id:'2946711'},{topic_id:'2946712'},{topic_id:'2946719'},{topic_id:'2946828'},{topic_id:'2946661'},{topic_id:'2946657'},{topic_id:'3150221'},{topic_id:'3150225'},{topic_id:'3190156'},{topic_id:'1210112'},{topic_id:'1210113'},{topic_id:'1629636'},{topic_id:'1210111'},{topic_id:'1210108'},{topic_id:'3143866'},{topic_id:'2889064'},{topic_id:'2889076'},{topic_id:'2889115'},{topic_id:'3143868'},{topic_id:'2889077'},{topic_id:'2902466'},{topic_id:'2902569'},{topic_id:'2902572'},{topic_id:'2902574'},{topic_id:'2902600'},{topic_id:'2902575'},{topic_id:'2902601'},{topic_id:'2902570'},{topic_id:'2902572'},{topic_id:'2902574'},{topic_id:'2902600'},{topic_id:'2902575'},{topic_id:'2902601'},{topic_id:'2902505'},{topic_id:'2902572'},{topic_id:'2902574'},{topic_id:'2902600'},{topic_id:'2902575'},{topic_id:'2902601'},{topic_id:'2902504'},{topic_id:'2902572'},{topic_id:'2902574'},{topic_id:'2902600'},{topic_id:'2902575'},{topic_id:'2902601'},{topic_id:'2902531'},{topic_id:'2889112'},{topic_id:'2889113'},{topic_id:'2946651'},{topic_id:'2946654'},{topic_id:'2946656'},{topic_id:'2946659'},{topic_id:'2946711'},{topic_id:'2946712'},{topic_id:'2946719'},{topic_id:'2946828'},{topic_id:'2946661'},{topic_id:'2946657'},{topic_id:'3150221'},{topic_id:'3150225'},{topic_id:'3190156'},{topic_id:'1210112'},{topic_id:'1210113'},{topic_id:'1629636'},{topic_id:'1210111'},{topic_id:'1210108'},{topic_id:'3143866'},{topic_id:'2889060'},{topic_id:'3088265'},{topic_id:'3105622'},{topic_id:'3087993',contact_options:{email_contact_form:'g_trademark',enable_chat:false,enable_c2c:false,show_immediately:true}},{topic_id:'3087986'},{topic_id:'3087987'},{topic_id:'3088266',contact_options:{email_contact_form:'reporting_malware',enable_chat:false,enable_c2c:false,show_immediately:true}},{topic_id:'3087988'},{topic_id:'3088267'}];var tsId='3087984';hcfeComponents.push([
'hcfe','escalation.Flow','.esc-flow-content',{'c2cAvail':c2cAvail,'chatFormId':chatFormId,'chatPoolId':chatPoolId,'contactParam':contactParam,'loginPrompt':loginPrompt,'nodeList':nodeList,'tsId':tsId
}
]);})();</script>   <script src="https://apis.google.com/js/client.js"></script>   <script src="//www.gstatic.com/support/content/20131031-164550-0748/js/hc-all.js"></script>    <script src="//www.gstatic.com/support/content/20131031-164550-0748/js/hc-csi-tail.js"></script>   <script>(function(){var analyticsId='UA-18500-19';var browser='other';var chatConfigured=false;var chatPoolId='';var country='';var debugParam='';var experiments=[];var feedbackProductId=0;var helpcenterExternalName='websearch';var helpcenterId='55';var helpcenterName='websearch';var host='support.google.com';var isInternal=false;var isLoggedIn=false;var isRtl=false;var lang='en';var os='other';var pageErrorType=0;var pageId='2664197';var pageType=1;var previewKey='';var pageViewId='0004ea957d689fa00ae5f8c296005942';var topDelayIntervals='-1';var hcfePage = new hcfe.page.Page();hcfePage.setVarsFromTemplate({analyticsId:analyticsId,browser:browser,chatConfigured:chatConfigured,chatPoolId:chatPoolId,components:hcfeComponents,country:country,debugParam:debugParam,pageViewId:pageViewId,experiments:experiments,feedbackProductId:feedbackProductId,hcfeStrings:hcfeStrings,helpcenterExternalName:helpcenterExternalName,helpcenterId:helpcenterId,helpcenterName:helpcenterName,host:host,isInternal:isInternal,isLoggedIn:isLoggedIn,isRtl:isRtl,lang:lang,os:os,pageErrorType:pageErrorType,pageId:pageId,pageType:pageType,previewKey:previewKey
});hcfePage.setServerFlagsFromTemplate({topDelayIntervals:topDelayIntervals
});hcfePage.decorate(document.body);})();</script>  <script src="https://www.google.com/js/maia.js"></script>   </body></html>'
    from /app/vendor/bundle/ruby/1.9.1/gems/json-1.8.1/lib/json/common.rb:155:in `parse'
    from /app/vendor/bundle/ruby/1.9.1/gems/json-1.8.1/lib/json/common.rb:155:in `parse'
    from /app/vendor/bundle/ruby/1.9.1/gems/goog_currency-1.0.2/lib/goog_currency.rb:26:in `method_missing'
    from (irb):6
    from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/commands/console.rb:47:in `start'
    from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/commands/console.rb:8:in `start'
    from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

**Comment by SimonBirrell** [comment]
This may be a useful alternative:

http://farebookings.blogspot.com.es/2013/11/currency-conversion-util.html

**Comment by girishso** [comment]
Hmm... the Google API seems to be retired now. Thanks for the heads up on farebookings!

**Comment by girishso** [comment]
Not using the API anymore, using Google Finance
